#!/usr/bin/env python3
"""Generate additive spawn content from reviewed retail initialization sightings.

No live database writes. The migration snapshots existing localized names before
inserting any variants, so it preserves locally restored populations as a unit.
"""
import collections, hashlib, importlib.util, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'evidence/enemy-restoration-2026-09-18'
MIGRATION = ROOT / 'db/direct-core/migrations/20260918_000044_captured_shroud_thanalan_enemies.sql'
GENUS = {'Monkey':4, 'Cactus':13, 'Spider':35, 'Bomb':64,
         'Orebeetle':49, 'Ogre':60, 'Lemming':12, 'Bat':43, 'Slug':21,
         'Petitghost':46, 'Chigoe':36, 'Mole':11, 'Firefly':38,
         'Funguar':14, 'Lizardman':23, 'Goblin':26}
EXISTING = {2100504,2101424,2102721,2102708,2103905,2104007,
            2104009,2104017,2104028,2104105,2107606}
DIRECTOR = {2202301,2202305,2204502}

def quote(value):
    return "'" + str(value).replace('\\','\\\\').replace("'","''") + "'"

def main():
    spec=importlib.util.spec_from_file_location('sheets',ROOT/'tools/Universal/recover-legacy-enemy-ids.py')
    sheets=importlib.util.module_from_spec(spec);spec.loader.exec_module(sheets)
    sheets.ROOT=Path('/Volumes/Dev2/SquareEnix/FINAL FANTASY XIV')
    names={r['id']:r['values'].get(1,'') for r in sheets.rows(189071360)}
    normalize=lambda s: s.strip().casefold()
    candidates=json.loads((ROOT/'evidence/trace-test-locations-2026-09-18/candidates.json').read_text())
    profiles=json.loads((ROOT/'evidence/npc-restoration-2026-09-15/battle-profile-observations.json').read_text())
    key=lambda p:(p['capture'],p['tcpStream'],p.get('frameIndex',p.get('frame')),p['actorClassId'],p['objectName'])
    lookup={key(p):p for p in profiles}
    selected=[]; skipped=[]; hashes={}
    for c in candidates:
        if c['kind']!='battle':continue
        cid=c['actorClassId']
        reason=('outside requested territories' if c['zoneId'] not in (150,151,152,154,162,172)
                else 'existing population' if cid in EXISTING
                else 'leve/director owned; not permanent ambient content' if cid in DIRECTOR else None)
        if reason:skipped.append(dict(candidateId=c['candidateId'],name=c['name'],reason=reason));continue
        p=lookup[key(c)]
        if c['capture'] not in hashes:
            hashes[c['capture']]=hashlib.sha256((ROOT/'ffxiv_traces'/c['capture']).read_bytes()).hexdigest()
        assert hashes[c['capture']]==p['captureSha256']
        assert '@%03X00'%c['zoneId'] in c['objectName']
        assert ('_fst0Fld' in c['objectName'] or '_wil0Fld' in c['objectName'])
        props=p['observedInitialProperties']
        value=lambda name: next(v for k,v in props['charaWork.parameterSave.'+name].items() if k!='size')
        for index in (0,1,2,4):assert props[f'charaWork.property[{index}]']['u8']==1
        r=dict(c,profile=p,level=value('state_mainSkillLevel'),hp=value('hpMax[0]'),mp=value('mpMax'),job=value('state_mainSkill[0]'))
        assert r['level']>0 and r['hp']>0
        r['genusId']=GENUS[p['classPath'].split('/')[4]]
        r['nameAliases']=[i for i,n in names.items() if normalize(n)==normalize(c['name'])]
        assert r['nameAliases']
        selected.append(r)
    sql=['-- Generated by prepare-trace-enemy-restoration.py; see companion evidence manifest.',
         '-- Captured sightings are TEST spawn origins, not proven home/respawn positions.',
         '-- Level/HP/MP/job/presentation are captured. Combat/respawn retain legacy defaults.',
         '-- No inferred drops, aggro, time/weather gates or retail combat formula claims.',
         'DROP TEMPORARY TABLE IF EXISTS tmp_trace_enemy_existing_names;',
         'CREATE TEMPORARY TABLE tmp_trace_enemy_existing_names AS SELECT DISTINCT a.displayNameId FROM gamedata_actor_class a JOIN (SELECT actorClassId FROM server_spawn_locations UNION SELECT p.actorClassId FROM server_battlenpc_pools p JOIN server_battlenpc_groups g USING(poolId) JOIN server_battlenpc_spawn_locations s USING(groupId)) existing ON existing.actorClassId=a.id;']
    poolids={};groupids={}
    events=quote(json.dumps({'talkEventConditions':[],'noticeEventConditions':[{'unknown1':0,'unknown2':1,'conditionName':'noticeEvent'}],'emoteEventConditions':[],'pushWithCircleEventConditions':[]}))
    for c in selected:
        cid=c['actorClassId'];p=c['profile'];aliases=','.join(map(str,c['nameAliases']))
        guard=f'NOT EXISTS (SELECT 1 FROM tmp_trace_enemy_existing_names WHERE displayNameId IN ({aliases}))'
        poolkey=(cid,c['job'])
        if poolkey not in poolids:
            pool=1844000+len(poolids);poolids[poolkey]=pool
            sql.append(f"UPDATE gamedata_actor_class SET classPath=IF(classPath='',{quote(p['classPath'])},classPath), propertyFlags=IF(propertyFlags=0,23,propertyFlags), eventConditions=IF(eventConditions IS NULL OR TRIM(eventConditions) IN ('','{{}}'),{events},eventConditions) WHERE id={cid} AND {guard};")
            sql.append(f"INSERT INTO server_battlenpc_pools (poolId,actorClassId,name,genusId,currentJob,combatSkill,combatDelay,combatDmgMult,aggroType,immunity,linkType,spellListId,skillListId) SELECT {pool},{cid},'trace_{cid}',{c['genusId']},{c['job']},1,4200,1,0,0,0,0,0 WHERE {guard};")
        pool=poolids[poolkey]
        groupkey=(pool,c['zoneId'],c['level'],c['hp'],c['mp'])
        if groupkey not in groupids:
            group=1844000+len(groupids);groupids[groupkey]=group
            sql.append(f"INSERT INTO server_battlenpc_groups (groupId,poolId,scriptName,minLevel,maxLevel,respawnTime,hp,mp,zoneId) SELECT {group},{pool},'trace_{cid}_{c['level']}',{c['level']},{c['level']+1},10,{c['hp']},{c['mp']},{c['zoneId']} WHERE {guard};")
        group=groupids[groupkey];spawn=1844000+selected.index(c)
        c.update(poolId=pool,groupId=group,bnpcId=spawn)
        sql.append(f"-- {c['candidateId']}: {c['name']}; {c['capture']} frame {c['frame']}; {c['objectName']}")
        sql.append(f"INSERT INTO server_battlenpc_spawn_locations (bnpcId,groupId,positionX,positionY,positionZ,rotation) SELECT {spawn},{group},{c['x']},{c['y']},{c['z']},{c['rotation']} WHERE {guard};")
    sql.append('DROP TEMPORARY TABLE tmp_trace_enemy_existing_names;')
    OUT.mkdir(parents=True,exist_ok=True)
    (OUT/'manifest.json').write_text(json.dumps(dict(selected=selected,skipped=skipped,captureHashes=hashes,policy='Captured initial sightings approved as test origins. Unknown retail behaviors retain existing defaults; no leve actors.'),indent=2)+'\n')
    MIGRATION.write_text('\n'.join(sql)+'\n')
    lines=['# Restored enemy test locations','', 'Captured sightings, not proven home positions. Respawn/combat use legacy defaults.','', '| Name | Zone | ID | X | Y | Z | Level | Candidate |','|---|---|---|---|---|---|---|---|']
    for c in selected:lines.append(f"| {c['name']} | {c['zoneName']} | {c['zoneId']} | {c['x']:.3f} | {c['y']:.3f} | {c['z']:.3f} | {c['level']} | {c['candidateId']} |")
    (OUT/'LOCATIONS.md').write_text('\n'.join(lines)+'\n')
    print('Prepared',len(selected),'placements;',len(poolids),'pools;',len(groupids),'profiles.',dict(collections.Counter(c['zoneId'] for c in selected)))

if __name__=='__main__':main()
