-- Treasures of the Main: missing Fishermen's lesson and smiths' echo.
-- Source: swstegall/Garlemald-Server 70e54f33fc4ea2473d6d82b46b6d0a4567fb2986,
-- common/sql/seed/058-061 (ported Project Meteor records).
-- Preserve source placements, including shared smith-cast coordinates; their
-- exact retail spacing remains unverified. Do not alter character progress.
START TRANSACTION;
INSERT INTO server_zones_privateareas (parentZoneId,className,privateAreaName,privateAreaType,dayMusic,nightMusic,battleMusic) SELECT 230,'/Area/PrivateArea/PrivateAreaMasterPast','PrivateAreaMasterPast',4,40,0,0 WHERE NOT EXISTS (SELECT 1 FROM server_zones_privateareas WHERE parentZoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaType=4);
INSERT INTO server_zones_privateareas (parentZoneId,className,privateAreaName,privateAreaType,dayMusic,nightMusic,battleMusic) SELECT 230,'/Area/PrivateArea/PrivateAreaMasterPast','PrivateAreaMasterPast',5,37,0,0 WHERE NOT EXISTS (SELECT 1 FROM server_zones_privateareas WHERE parentZoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaType=5);
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000145,'man0l1_hnaanza',230,'PrivateAreaMasterPast',4,-506.842,42.49,432.026,1.078,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_hnaanza');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000111,'man0l1_tattooed_pirate',230,'PrivateAreaMasterPast',4,-479,41.505,433.188,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_tattooed_pirate');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000144,'man0l1_bodenolf',230,'PrivateAreaMasterPast',4,-500.06,42.8,416.06,1.19,0,1016,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_bodenolf');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000163,'man0l1_joellaut',230,'PrivateAreaMasterPast',4,-479,41.505,433.188,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_joellaut');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000176,'man0l1_mimidoa',230,'PrivateAreaMasterPast',4,-483.67,44.5,404.51,0.793,0,1015,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_mimidoa');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000247,'man0l1_werner',230,'PrivateAreaMasterPast',4,-479,41.505,433.188,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_werner');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000267,'man0l1_hihine',230,'PrivateAreaMasterPast',4,-479,41.505,433.188,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_hihine');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000268,'man0l1_trinne',230,'PrivateAreaMasterPast',4,-479,41.505,433.188,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_trinne');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000135,'man0l1_iofa',230,'PrivateAreaMasterPast',4,-490.59,42.8,420.71,-1.74,0,1016,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_iofa');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000061,'man0l1_mzimzizi',230,'PrivateAreaMasterPast',4,-489.4,42.95,415.4,-2.28,0,2016,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_mzimzizi');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000060,'man0l1_pfynhaemr',230,'PrivateAreaMasterPast',4,-492.26,42.8,414.65,1.4,0,2015,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_pfynhaemr');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000062,'man0l1_carrilaut',230,'PrivateAreaMasterPast',4,-486.69,42.8,411.36,-0.78,0,2017,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_carrilaut');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 5900001,'man0l1_bsm_west_door',230,'PrivateAreaMasterPast',4,-498,43,424,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_bsm_west_door');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 5900001,'man0l1_bsm_east_door',230,'PrivateAreaMasterPast',4,-477,45,403,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_bsm_east_door');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1090007,'man0l1_trigger_armbsm',230,'PrivateAreaMasterPast',4,-490.38,42.8,417.81,2.45,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_trigger_armbsm');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1290002,'man0l1_privatearea_exit',230,'PrivateAreaMasterPast',4,-485,42.8,414,0,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=4 AND uniqueId='man0l1_privatearea_exit');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000155,'man0l1_fsh_sisipu',230,'PrivateAreaMasterPast',5,-617.56,4.55,344.91,1.11,0,0,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_sisipu');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000165,'man0l1_fsh_louviaune',230,'PrivateAreaMasterPast',5,-616.7,4.55,342.49,-0.28,0,1017,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_louviaune');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000164,'man0l1_fsh_faucillien',230,'PrivateAreaMasterPast',5,-614.73,4.55,342.24,0.14,0,1015,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_faucillien');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000153,'man0l1_fsh_nnmulika',230,'PrivateAreaMasterPast',5,-612.9,4.55,341.42,0.69,0,1017,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_nnmulika');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000199,'man0l1_fsh_clifton',230,'PrivateAreaMasterPast',5,-618.03,4.55,353.03,-2.4,0,1017,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_clifton');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000202,'man0l1_fsh_daca_jinjahl',230,'PrivateAreaMasterPast',5,-624.77,4.25,354.05,-3.06,0,1070,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_daca_jinjahl');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000203,'man0l1_fsh_bloemerl',230,'PrivateAreaMasterPast',5,-624.67,4.25,352.67,-0.08,0,1033,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_bloemerl');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000200,'man0l1_fsh_undsatz',230,'PrivateAreaMasterPast',5,-608.92,4.55,342.55,1.79,0,1017,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_undsatz');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000180,'man0l1_fsh_astrid',230,'PrivateAreaMasterPast',5,-606.7,4.55,349.59,-0.83,0,1041,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_astrid');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000181,'man0l1_fsh_xavalien',230,'PrivateAreaMasterPast',5,-598.59,6.25,356.57,-0.79,0,1041,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_xavalien');
INSERT INTO server_spawn_locations (actorClassId,uniqueId,zoneId,privateAreaName,privateAreaLevel,positionX,positionY,positionZ,rotation,actorState,animationId,customDisplayName) SELECT 1000173,'man0l1_fsh_maisie',230,'PrivateAreaMasterPast',5,-603.64,6.25,355.46,-0.75,0,1015,NULL WHERE NOT EXISTS (SELECT 1 FROM server_spawn_locations WHERE zoneId=230 AND privateAreaName='PrivateAreaMasterPast' AND privateAreaLevel=5 AND uniqueId='man0l1_fsh_maisie');
UPDATE gamedata_actor_class SET `classPath`='/Chara/Npc/Populace/PopulaceStandard', `displayNameId`=4000035, `propertyFlags`=19 WHERE id=1000111 AND (classPath IS NULL OR TRIM(classPath)='');
UPDATE gamedata_actor_class SET `classPath`='/Chara/Npc/Populace/PopulaceStandard', `displayNameId`=1900029, `propertyFlags`=19 WHERE id=1000145 AND (classPath IS NULL OR TRIM(classPath)='');
UPDATE gamedata_actor_class SET `classPath`='/Chara/Npc/Populace/PopulaceStandard', `displayNameId`=1500024, `propertyFlags`=19 WHERE id=1000155 AND (classPath IS NULL OR TRIM(classPath)='');
UPDATE gamedata_actor_class SET `classPath`='/Chara/Npc/Populace/PopulaceStandard', `displayNameId`=1400012, `propertyFlags`=19 WHERE id=1000176 AND (classPath IS NULL OR TRIM(classPath)='');
UPDATE gamedata_actor_class SET `classPath`='/Chara/Npc/Populace/PopulaceStandard', `displayNameId`=1000028, `propertyFlags`=19 WHERE id=1000247 AND (classPath IS NULL OR TRIM(classPath)='');
UPDATE gamedata_actor_class SET eventConditions='{"talkEventConditions":[{"unknown1":4,"unknown2":0,"conditionName":"talkDefault"}],"noticeEventConditions":[{"unknown1":0,"unknown2":1,"conditionName":"noticeEvent"}]}' WHERE id=1000111 AND (eventConditions IS NULL OR TRIM(eventConditions) IN ('','{}'));
UPDATE gamedata_actor_class SET eventConditions='{"talkEventConditions":[{"unknown1":4,"unknown2":0,"conditionName":"talkDefault"}],"noticeEventConditions":[{"unknown1":0,"unknown2":1,"conditionName":"noticeEvent"}]}' WHERE id=1000145 AND (eventConditions IS NULL OR TRIM(eventConditions) IN ('','{}'));
UPDATE gamedata_actor_class SET eventConditions='{"talkEventConditions":[{"unknown1":4,"unknown2":0,"conditionName":"talkDefault"}],"noticeEventConditions":[{"unknown1":0,"unknown2":1,"conditionName":"noticeEvent"}],"emoteEventConditions":[{"unknown1":4,"unknown2":0,"emoteId":105,"conditionName":"emoteDefault1"},{"unknown1":4,"unknown2":0,"emoteId":107,"conditionName":"emoteDefault2"},{"unknown1":4,"unknown2":0,"emoteId":129,"conditionName":"emoteDefault3"},{"unknown1":4,"unknown2":0,"emoteId":128,"conditionName":"emoteDefault4"},{"unknown1":4,"unknown2":0,"emoteId":118,"conditionName":"emoteDefault5"},{"unknown1":4,"unknown2":0,"emoteId":116,"conditionName":"emoteDefault6"}]}' WHERE id=1000155 AND (eventConditions IS NULL OR TRIM(eventConditions) IN ('','{}'));
UPDATE gamedata_actor_class SET eventConditions='{"talkEventConditions":[{"unknown1":4,"unknown2":0,"conditionName":"talkDefault"}],"noticeEventConditions":[{"unknown1":0,"unknown2":1,"conditionName":"noticeEvent"}]}' WHERE id=1000176 AND (eventConditions IS NULL OR TRIM(eventConditions) IN ('','{}'));
UPDATE gamedata_actor_class SET eventConditions='{"talkEventConditions":[{"unknown1":4,"unknown2":0,"conditionName":"talkDefault"}],"noticeEventConditions":[{"unknown1":0,"unknown2":1,"conditionName":"noticeEvent"}]}' WHERE id=1000247 AND (eventConditions IS NULL OR TRIM(eventConditions) IN ('','{}'));
COMMIT;
