/*
 * AetherXIV
 * Copyright (C) 2026 Demi Dev Unit
 *
 * This file is part of AetherXIV.
 * See THIRD_PARTY_NOTICES.md for historical and third-party attribution.
 *
 * AetherXIV is free software: you may redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace Aether.Umbra.Framework;

/// <summary>
/// Pure, portable machine-code generator for the in-process code breakpoints
/// exposed by the development bridge.
///
/// A breakpoint is implemented as a 5-byte relative-jump detour (no INT3, no
/// vectored exception handler, no single-step re-arm). The detour lands in a
/// generated stub that:
///
///   mov [captureBefore], eax   ; save EAX at detour entry
///   mov [captureEsp], esp      ; save ESP (the original instruction's frame)
///   mov [captureEsi], esi      ; save ESI (X/"this" in the tutorial handlers)
///   mov [captureEdi], edi      ; save EDI (Y at the field_8 attach store)
///   mov [captureEcx], ecx      ; save ECX (the object pointer at detour
///                              ; entry — the vtable-dispatch plan's `this`)
///   &lt;relocated head bytes&gt;     ; the original instruction(s) up to the
///                              ; point of interest
///   mov [captureAfter], eax    ; save EAX after the head ran
///   inc dword [captureCount]   ; hit counter (flags are clobbered here, but…)
///   &lt;relocated tail bytes&gt;     ; …the relocated tail re-sets the flags
///                              ; before the jump-back for flag-sensitive
///                              ; branches (the tutorial-mode plan's cmp)
///   jmp rel32 → jump-back      ; resume at the instruction after the range
///
/// Register and flag state is preserved exactly: every generated instruction
/// except <c>inc</c> leaves the flags untouched, and <c>inc</c> is followed by
/// the relocated tail, so a tail <c>cmp</c> re-establishes EFLAGS before the
/// jump-back branch. The counter is written last, so a poller that observes a
/// changed count always sees a fully-written register snapshot. This class has
/// no Windows dependency and is compiled into the portable test project so the
/// generated bytes can be verified on a non-Windows host.
/// </summary>
public static class UmbraBreakpointStubBuilder
{
    /// <summary>Size of the relative-jump patch written at the target.</summary>
    public const int PatchLength = 5;

    /// <summary>
    /// Builds the 5-byte <c>jmp rel32</c> patch placed at the target address.
    /// </summary>
    public static byte[] BuildPatch(uint targetAddress, uint stubAddress)
    {
        byte[] patch = new byte[PatchLength];
        patch[0] = 0xE9;
        // The rel32 offset intentionally wraps to its two's-complement value;
        // unchecked makes that explicit under any overflow-checked build.
        WriteUInt32(patch, 1, unchecked(stubAddress - (targetAddress + PatchLength)));
        return patch;
    }

    /// <summary>
    /// Builds the detour stub described in the class summary. All addresses are
    /// absolute virtual addresses in the (32-bit) client process.
    /// </summary>
    /// <param name="stubAddress">Virtual address where the stub will be placed.</param>
    /// <param name="captureBefore">Absolute address of the EAX-before slot.</param>
    /// <param name="captureAfter">Absolute address of the EAX-after slot.</param>
    /// <param name="captureEsp">Absolute address of the ESP slot.</param>
    /// <param name="captureEsi">Absolute address of the ESI slot.</param>
    /// <param name="captureEdi">Absolute address of the EDI slot.</param>
    /// <param name="captureEcx">Absolute address of the ECX slot (the <c>this</c>
    /// pointer at detour entry — the vtable-dispatch plan's object).</param>
    /// <param name="captureCount">Absolute address of the hit-counter slot.</param>
    /// <param name="headBytes">Relocated original instruction(s) run before the EAX-after capture.</param>
    /// <param name="tailBytes">Relocated original instruction(s) run after the EAX-after capture.</param>
    /// <param name="jumpBackAddress">Virtual address to resume at (after the relocated range).</param>
    public static byte[] BuildStub(
        uint stubAddress,
        uint captureBefore,
        uint captureAfter,
        uint captureEsp,
        uint captureEsi,
        uint captureEdi,
        uint captureEcx,
        uint captureCount,
        byte[] headBytes,
        byte[] tailBytes,
        uint jumpBackAddress)
    {
        var code = new List<byte>(capacity: headBytes.Length + tailBytes.Length + 54);

        // mov [captureBefore], eax        (A3 imm32, 5 bytes)
        code.Add(0xA3);
        AppendUInt32(code, captureBefore);

        // mov [captureEsp], esp           (89 25 imm32, 6 bytes)
        code.Add(0x89);
        code.Add(0x25);
        AppendUInt32(code, captureEsp);

        // mov [captureEsi], esi           (89 35 imm32, 6 bytes)
        code.Add(0x89);
        code.Add(0x35);
        AppendUInt32(code, captureEsi);

        // mov [captureEdi], edi           (89 3D imm32, 6 bytes)
        code.Add(0x89);
        code.Add(0x3D);
        AppendUInt32(code, captureEdi);

        // mov [captureEcx], ecx           (89 0D imm32, 6 bytes)
        code.Add(0x89);
        code.Add(0x0D);
        AppendUInt32(code, captureEcx);

        // Relocated instruction(s) up to the capture point.
        code.AddRange(headBytes);

        // mov [captureAfter], eax         (A3 imm32, 5 bytes)
        code.Add(0xA3);
        AppendUInt32(code, captureAfter);

        // inc dword [captureCount]        (FF 05 imm32, 6 bytes)
        code.Add(0xFF);
        code.Add(0x05);
        AppendUInt32(code, captureCount);

        // Remaining relocated instruction(s) — for the tutorial-mode plan this
        // is the cmp that re-establishes EFLAGS for the jump-back branch.
        code.AddRange(tailBytes);

        // jmp rel32 → jumpBackAddress     (E9 rel32, 5 bytes)
        int jumpOperandOffset = code.Count;
        code.Add(0xE9);
        uint relative = unchecked(
            jumpBackAddress - (stubAddress + (uint)(jumpOperandOffset + PatchLength)));
        AppendUInt32(code, relative);

        return code.ToArray();
    }

    /// <summary>
    /// Builds the detour stub for the Lua VM call hook, installed at the
    /// <c>luaD_precall</c> entry (<c>ffxivgame.exe+0x9cfa60</c>). The stub
    /// runs on <em>every</em> Lua call. At entry <c>esp</c> is the original
    /// entry stack, so <c>[esp+8]</c> is <c>func</c> (a 16-byte TValue whose
    /// value is a <c>Closure*</c> at +0 and whose tag is at +8). The walk is:
    ///
    /// <code>
    ///   func     = [esp+8]
    ///   tag      = [func+8]          ; 6 == LUA_TFUNCTION
    ///   closure  = [func]            ; Closure*
    ///   if tag != 6  → not a Lua function, done
    ///   if [closure+6] != 0  → isC, a C closure, done
    ///   proto    = [closure+0x10]
    ///   linedef  = [proto+0x3C]      ; Proto.linedefined
    ///   lastline = [proto+0x40]      ; Proto.lastlinedefined
    /// </code>
    ///
    /// The line range is then matched against the two tutorial-mode closures
    /// and the matching counter is incremented. Because the counters only
    /// move when one of the two rare closures runs, a poller that reads on
    /// counter change reports exactly the <c>isTutorialMode</c> /
    /// <c>orderTutorialMode</c> call sequence and never floods on the
    /// ordinary call traffic. The relocated head/tail re-establish
    /// <c>eax == func</c> and the original <c>cmp</c> flags before the
    /// jump-back, so the caller's <c>je</c> at 0x9cfa6f is untouched.
    /// </summary>
    public const int LuaCallRecordRingCapacity = 16;
    public const int LuaCallRecordSize = 48;
    public const int LuaCallRecordRingOffset = 0x400;

    public static byte[] BuildLuaCallStub(
        uint stubAddress,
        uint captureEsp,
        uint captureFunc,
        uint captureClosure,
        uint captureProto,
        uint captureLineDef,
        uint captureLastLine,
        uint captureTag,
        uint captureCountIsTutorialMode,
        uint captureCountOrderTutorialMode,
        uint captureCountOtherLua,
        uint captureTotalHits,
        uint captureRecordCursor,
        uint captureTimestampLow,
        uint captureTimestampHigh,
        uint captureThreadId,
        uint captureMatchKind,
        uint captureRecordRing,
        uint jumpBackAddress)
    {
        var code = new List<byte>(capacity: 420);

        // Preserve every general-purpose register while inspecting the Lua
        // value. The original luaD_precall entry only changes EAX and EFLAGS
        // before its first branch; clobbering ECX/EDX here would change the
        // callee's behavior even though this detour is observational only.
        code.Add(0x60); // pushad; original ESP is now [esp+0x0C]
        code.AddRange(new byte[] { 0x8D, 0x44, 0x24, 0x20 }); // lea eax,[esp+32] (original ESP)
        code.Add(0xA3); AppendUInt32(code, captureEsp);
        code.AddRange(new byte[] { 0x83, 0xEC, 0x2C }); // sub esp, 44

        // func = original [esp+8] = current [esp+0x54].
        code.AddRange(new byte[] { 0x8B, 0x44, 0x24, 0x54 });
        code.Add(0x89); code.AddRange(new byte[] { 0x44, 0x24, 0x00 });
        code.Add(0xA3); AppendUInt32(code, captureFunc);
        code.AddRange(new byte[] { 0x85, 0xC0 });
        int jeNull = EmitNearJcc(code, 0x84);

        // tag = func->tag; only function values can be walked further.
        code.AddRange(new byte[] { 0x8B, 0x48, 0x08 });
        code.Add(0x89); code.AddRange(new byte[] { 0x4C, 0x24, 0x04 });
        code.Add(0x89); code.Add(0x0D); AppendUInt32(code, captureTag);
        code.AddRange(new byte[] { 0x83, 0xF9, 0x06 });
        int jneTag = EmitNearJcc(code);

        // closure = func->value.
        code.AddRange(new byte[] { 0x8B, 0x00 });
        code.Add(0x89); code.AddRange(new byte[] { 0x44, 0x24, 0x08 });
        code.Add(0xA3); AppendUInt32(code, captureClosure);
        code.AddRange(new byte[] { 0x85, 0xC0 });
        int jeClosure = EmitNearJcc(code, 0x84);
        code.AddRange(new byte[] { 0x80, 0x78, 0x06, 0x00 });
        int jneCClosure = EmitNearJcc(code);

        // proto = closure->proto, then the verified line range.
        code.AddRange(new byte[] { 0x8B, 0x40, 0x10 });
        code.Add(0x89); code.AddRange(new byte[] { 0x44, 0x24, 0x0C });
        code.Add(0xA3); AppendUInt32(code, captureProto);
        code.AddRange(new byte[] { 0x85, 0xC0 });
        int jeProto = EmitNearJcc(code, 0x84);
        code.AddRange(new byte[] { 0x8B, 0x50, 0x3C });
        code.Add(0x89); code.AddRange(new byte[] { 0x54, 0x24, 0x10 });
        code.Add(0x89); code.Add(0x15); AppendUInt32(code, captureLineDef);
        code.AddRange(new byte[] { 0x8B, 0x48, 0x40 });
        code.Add(0x89); code.AddRange(new byte[] { 0x4C, 0x24, 0x14 });
        code.Add(0x89); code.Add(0x0D); AppendUInt32(code, captureLastLine);

        // isTutorialMode range.
        code.Add(0x81); code.Add(0xFA); AppendUInt32(code, (uint)UmbraLuaCallHookPlan.IsTutorialModeLineDefined);
        int jneOrder = EmitNearJcc(code);
        code.Add(0x81); code.Add(0xF9); AppendUInt32(code, (uint)UmbraLuaCallHookPlan.IsTutorialModeLastLineDefined);
        int jneOrderLast = EmitNearJcc(code);
        code.Add(0xC7); code.Add(0x44); code.Add(0x24); code.Add(0x18); AppendUInt32(code, 1);
        int jmpRecordIs = EmitNearJmp(code);

        // orderTutorialMode range.
        int orderLabel = code.Count;
        code.Add(0x81); code.Add(0xFA); AppendUInt32(code, (uint)UmbraLuaCallHookPlan.OrderTutorialModeLineDefined);
        int jneExitLine = EmitNearJcc(code);
        code.Add(0x81); code.Add(0xF9); AppendUInt32(code, (uint)UmbraLuaCallHookPlan.OrderTutorialModeLastLineDefined);
        int jneExitLast = EmitNearJcc(code);
        code.Add(0xC7); code.Add(0x44); code.Add(0x24); code.Add(0x18); AppendUInt32(code, 2);
        int jmpRecordOrder = EmitNearJmp(code);

        int record = code.Count;
        // Timestamp/thread and one atomic sequence are captured at the actual
        // matched call, not when the managed bridge happens to poll.
        code.Add(0x0F); code.Add(0x31);
        code.Add(0x89); code.AddRange(new byte[] { 0x44, 0x24, 0x1C });
        code.Add(0x89); code.AddRange(new byte[] { 0x54, 0x24, 0x20 });
        code.AddRange(new byte[] { 0x64, 0x8B, 0x0D, 0x24, 0x00, 0x00, 0x00 });
        code.Add(0x89); code.AddRange(new byte[] { 0x4C, 0x24, 0x24 });

        code.AddRange(new byte[] { 0xB8, 0x01, 0x00, 0x00, 0x00 });
        code.Add(0xF0); code.Add(0x0F); code.Add(0xC1); code.Add(0x05); AppendUInt32(code, captureRecordCursor);
        code.Add(0x40); // sequence = old cursor + 1
        code.Add(0x89); code.AddRange(new byte[] { 0x44, 0x24, 0x28 });
        code.Add(0x89); code.Add(0xC1); // ECX = sequence
        code.Add(0x81); code.Add(0xE1); AppendUInt32(code, (uint)(LuaCallRecordRingCapacity - 1));
        code.Add(0x8D); code.Add(0x04); code.Add(0x49); // slot * 3
        code.Add(0xC1); code.Add(0xE0); code.Add(0x04); // slot * 48
        code.Add(0xBA); AppendUInt32(code, captureRecordRing);
        code.Add(0x01); code.Add(0xC2); // EDX = ring slot

        EmitLocalToRecord(code, 0x1C, 4);  // timestamp low
        EmitLocalToRecord(code, 0x20, 8);  // timestamp high
        EmitLocalToRecord(code, 0x24, 12); // thread id
        EmitLocalToRecord(code, 0x18, 16); // match kind
        EmitLocalToRecord(code, 0x00, 20); // func
        EmitLocalToRecord(code, 0x04, 24); // tag
        EmitLocalToRecord(code, 0x08, 28); // closure
        EmitLocalToRecord(code, 0x0C, 32); // proto
        EmitLocalToRecord(code, 0x10, 36); // line
        EmitLocalToRecord(code, 0x14, 40); // last line
        // ESP is the original entry ESP, captured before the local frame.
        code.Add(0xA1); AppendUInt32(code, captureEsp);
        code.Add(0x89); code.Add(0x42); code.Add(0x2C);
        // Commit sequence only after every record field is written.
        code.Add(0x8B); code.AddRange(new byte[] { 0x44, 0x24, 0x28 });
        code.Add(0x89); code.Add(0x02);

        // Keep the legacy counters, but update them after the committed record.
        code.AddRange(new byte[] { 0x83, 0x7C, 0x24, 0x18, 0x01 });
        int jneCountOrder = EmitNearJcc(code);
        code.Add(0xFF); code.Add(0x05); AppendUInt32(code, captureCountIsTutorialMode);
        int jmpEpilogue = EmitNearJmp(code);
        int countOrder = code.Count;
        code.Add(0xFF); code.Add(0x05); AppendUInt32(code, captureCountOrderTutorialMode);

        int epilogue = code.Count;
        code.Add(0x83); code.Add(0xC4); code.Add(0x2C); // release locals
        code.Add(0x61); // popad; restore every register from detour entry
        code.Add(0xFF); code.Add(0x05); AppendUInt32(code, captureTotalHits);
        code.AddRange(new byte[] { 0x8B, 0x44, 0x24, 0x08 }); // relocated head
        code.AddRange(new byte[] { 0x83, 0x78, 0x08, 0x06 }); // relocated tail
        int jumpOperandOffset = code.Count;
        code.Add(0xE9); AppendUInt32(code, unchecked(jumpBackAddress - (stubAddress + (uint)(jumpOperandOffset + PatchLength))));

        PatchRel32(code, jeNull, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jneTag, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jeClosure, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jneCClosure, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jeProto, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jneOrder, 6, stubAddress, (uint)orderLabel);
        PatchRel32(code, jneOrderLast, 6, stubAddress, (uint)orderLabel);
        PatchRel32(code, jmpRecordIs, 5, stubAddress, (uint)record);
        PatchRel32(code, jneExitLine, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jneExitLast, 6, stubAddress, (uint)epilogue);
        PatchRel32(code, jmpRecordOrder, 5, stubAddress, (uint)record);
        PatchRel32(code, jneCountOrder, 6, stubAddress, (uint)countOrder);
        PatchRel32(code, jmpEpilogue, 5, stubAddress, (uint)epilogue);

        return code.ToArray();
    }

    private static void EmitLocalToRecord(List<byte> code, int sourceOffset, int destinationOffset)
    {
        // mov EAX,[ESP+sourceOffset]; mov [EDX+destinationOffset],EAX
        if ((uint)sourceOffset > byte.MaxValue || (uint)destinationOffset > byte.MaxValue)
            throw new ArgumentOutOfRangeException();

        code.AddRange(new byte[] { 0x8B, 0x44, 0x24, (byte)sourceOffset });
        code.AddRange(new byte[] { 0x89, 0x42, (byte)destinationOffset });
    }

    private static void EmitLoadStore(List<byte> code, uint source, int destinationOffset)
    {
        code.Add(0xA1); // mov EAX,[source]
        AppendUInt32(code, source);
        code.Add(0x89);
        code.Add(0x42); // mov [EDX+disp8],EAX
        code.Add((byte)destinationOffset);
    }

    private static int EmitNearJcc(List<byte> code)
    {
        return EmitNearJcc(code, 0x85);
    }

    private static int EmitNearJcc(List<byte> code, byte conditionOpcode)
    {
        if (conditionOpcode < 0x80 || conditionOpcode > 0x8F)
            throw new ArgumentOutOfRangeException(nameof(conditionOpcode));

        int start = code.Count;
        code.AddRange(new byte[] { 0x0F, conditionOpcode, 0x00, 0x00, 0x00, 0x00 });
        return start;
    }

    private static int EmitNearJmp(List<byte> code)
    {
        int start = code.Count;
        code.AddRange(new byte[] { 0xE9, 0x00, 0x00, 0x00, 0x00 });
        return start;
    }

    private static void PatchRel32(List<byte> code, int instructionStart, int instructionLength, uint stubAddress, uint labelOffset)
    {
        // labelOffset is the byte offset of the jump target within the stub;
        // its absolute virtual address is stubAddress + labelOffset.
        uint next = stubAddress + (uint)(instructionStart + instructionLength);
        uint target = stubAddress + labelOffset;
        uint rel = unchecked(target - next);
        int operand = instructionStart + instructionLength - 4;
        code[operand] = (byte)(rel & 0xFF);
        code[operand + 1] = (byte)((rel >> 8) & 0xFF);
        code[operand + 2] = (byte)((rel >> 16) & 0xFF);
        code[operand + 3] = (byte)((rel >> 24) & 0xFF);
    }

    private static void AppendUInt32(List<byte> buffer, uint value)
    {
        buffer.Add((byte)(value & 0xFF));
        buffer.Add((byte)((value >> 8) & 0xFF));
        buffer.Add((byte)((value >> 16) & 0xFF));
        buffer.Add((byte)((value >> 24) & 0xFF));
    }

    private static void WriteUInt32(byte[] buffer, int offset, uint value)
    {
        buffer[offset] = (byte)(value & 0xFF);
        buffer[offset + 1] = (byte)((value >> 8) & 0xFF);
        buffer[offset + 2] = (byte)((value >> 16) & 0xFF);
        buffer[offset + 3] = (byte)((value >> 24) & 0xFF);
    }
}

/// <summary>
/// Describes one code breakpoint: the module-relative address, the exact bytes
/// expected at that address (a build-safety check performed before patching),
/// and the original instruction bytes to relocate into the capture stub.
/// </summary>
public sealed record UmbraBreakpointPlan(
    string Name,
    string? Module,
    uint Offset,
    byte[] ExpectedBytes,
    byte[] HeadBytes,
    byte[] TailBytes)
{
    /// <summary>Module-relative address to resume at after the relocated range.</summary>
    public uint JumpBackOffset => Offset + (uint)(HeadBytes.Length + TailBytes.Length);

    /// <summary>
    /// ffxivgame.exe+0x497358. The tutorial-mode handler loads the mode byte
    /// (<c>mov al,[esp+0x38]</c>) before comparing it against
    /// <c>g[0x12d7c40]</c> (<c>mode == 1</c> arms <c>X-&gt;field_8</c>). Capturing
    /// EAX after that <c>mov</c> records the mode value the handler observed,
    /// and ESI (saved from ECX at <c>0x897337</c>) records the real <c>X</c>
    /// object address — the object whose <c>field_8</c> the Confirm path
    /// dereferences.
    /// </summary>
    public static UmbraBreakpointPlan TutorialModeConfirm { get; } = new(
        "tutorial-mode-confirm",
        Module: null, // main module (ffxivgame.exe)
        Offset: 0x497358,
        ExpectedBytes: new byte[]
        {
            0x8A, 0x44, 0x24, 0x38, // mov al, [esp+0x38]
            0x3A, 0x05, 0x95, 0x52, 0x35, 0x01 // cmp al, [0x1355295]
        },
        HeadBytes: new byte[]
        {
            0x8A, 0x44, 0x24, 0x38 // mov al, [esp+0x38]
        },
        TailBytes: new byte[]
        {
            0x3A, 0x05, 0x95, 0x52, 0x35, 0x01 // cmp al, [0x1355295]
        });

    /// <summary>
    /// ffxivgame.exe+0x4973CB. The mode==1 attach arm stores the new sub-object:
    /// <c>mov [esi+0x8],edi</c> (<c>X-&gt;field_8 = Y</c>) followed by
    /// <c>add esi,0x4</c>. ESI holds <c>X</c> (saved from ECX at 0x897337) and
    /// EDI holds <c>Y</c> (or zero when the 0x2c allocation failed). This is
    /// the single instruction that arms <c>field_8</c>, so a hit here with a
    /// non-zero <c>Y</c> proves the attach actually happened and names the
    /// exact <c>X</c> to watch at the Confirm click.
    /// </summary>
    public static UmbraBreakpointPlan TutorialModeAttach { get; } = new(
        "tutorial-mode-attach",
        Module: null, // main module (ffxivgame.exe)
        Offset: 0x4973CB,
        ExpectedBytes: new byte[]
        {
            0x89, 0x7E, 0x08, // mov [esi+0x8], edi  (X->field_8 = Y)
            0x83, 0xC6, 0x04 // add esi, 0x4
        },
        HeadBytes: new byte[]
        {
            0x89, 0x7E, 0x08 // mov [esi+0x8], edi  (the store itself)
        },
        TailBytes: new byte[]
        {
            0x83, 0xC6, 0x04 // add esi, 0x4
        });

    /// <summary>
    /// ffxivgame.exe+0x497541. Inside the 0x497530 wrapper, immediately after
    /// <c>call edx</c> (S->vtbl[7](), the "enabled" predicate) and before the
    /// <c>cmp al,0x1</c> gate at 0x497549. AL holds the predicate result
    /// (1 = modeChange 0x497310 will run, 0 = the else branch 0x496510), so
    /// <c>mode_byte</c> names the gate decision. ESI holds S (the mode-source
    /// object) and EDI holds X (the ItemCommandBase, saved from ECX at
    /// 0x49753B). The two relocated movs read the same ESP-relative stack
    /// slots in the stub, and execution resumes at the cmp, which
    /// re-establishes the flags for the branch.
    /// </summary>
    public static UmbraBreakpointPlan TutorialModeGate { get; } = new(
        "tutorial-mode-gate",
        Module: null, // main module (ffxivgame.exe)
        Offset: 0x497541,
        ExpectedBytes: new byte[]
        {
            0x8B, 0x4C, 0x24, 0x14, // mov ecx, [esp+0x14]
            0x8B, 0x54, 0x24, 0x10 // mov edx, [esp+0x10]
        },
        HeadBytes: new byte[]
        {
            0x8B, 0x4C, 0x24, 0x14 // mov ecx, [esp+0x14]
        },
        TailBytes: new byte[]
        {
            0x8B, 0x54, 0x24, 0x10 // mov edx, [esp+0x10]
        });

    /// <summary>
    /// ffxivgame.exe+0x3493E0. The scalar-deleting-destructor dispatch target
    /// of the class whose vtable sits at 0xFD785C (a ~0x168-byte object with
    /// key-loading methods; the live Confirm crash unwinds through this
    /// vtable). The crash is a NULL+4 deref (<c>movl 4(%ecx),%ecx</c> with
    /// ECX=0) on a virtual call dispatched through this vtable, so a hit here
    /// with <c>this</c> (ECX, captured at detour entry) == 0 names the NULL
    /// object. The head (<c>push esi; mov ecx,esi</c>) preserves ECX for the
    /// capture and re-establishes ESI==this before the tail <c>call</c> runs.
    /// </summary>
    public static UmbraBreakpointPlan VtableFd785cDispatch { get; } = new(
        "vtable-fd785c-dispatch",
        Module: null, // main module (ffxivgame.exe)
        Offset: 0x3493E0,
        ExpectedBytes: new byte[]
        {
            0x56, // push esi
            0x8B, 0xF1, // mov ecx, esi
            0xE8, 0x28, 0xFF, 0xFA, 0xFF // call 0x6F9310
        },
        HeadBytes: new byte[]
        {
            0x56, // push esi
            0x8B, 0xF1 // mov ecx, esi
        },
        TailBytes: new byte[]
        {
            0xE8, 0x28, 0xFF, 0xFA, 0xFF // call 0x6F9310
        });
}

/// <summary>
/// Describes the Lua VM call hook: a detour at the <c>luaD_precall</c> entry
/// that walks the <c>func</c> TValue to the called closure's <c>Proto</c> and
/// counts the two tutorial-mode closures by their source line range (the only
/// stable identifier — the chunk serializes no locvars and its per-function
/// <c>source</c> strings are empty).
/// </summary>
public sealed record UmbraLuaCallHookPlan(
    string Name,
    uint Offset,
    byte[] ExpectedBytes,
    byte[] HeadBytes,
    byte[] TailBytes)
{
    /// <summary>
    /// <c>DesktopWidget:isTutorialMode</c> = <c>return self.work.tutorialFlag</c>.
    /// Preorder proto 156 of <c>desktopwidget_connector.luac</c>,
    /// source lines 7165..7167.
    /// </summary>
    public const int IsTutorialModeLineDefined = 7165;

    public const int IsTutorialModeLastLineDefined = 7167;

    /// <summary>
    /// <c>DesktopWidget:orderTutorialMode</c> — sets
    /// <c>self.work.tutorialFlag = true</c> and orders desktop mode 120.
    /// Preorder proto 153, source lines 7020..7034.
    /// </summary>
    public const int OrderTutorialModeLineDefined = 7020;

    public const int OrderTutorialModeLastLineDefined = 7034;

    public uint JumpBackOffset => Offset + (uint)(HeadBytes.Length + TailBytes.Length);

    /// <summary>
    /// ffxivgame.exe+0x9cfa60 (<c>luaD_precall</c>):
    /// <c>mov eax,[esp+8]</c> (func) then <c>cmp [eax+8],6</c>
    /// (<c>ttisfunction</c>). <c>func</c> is the second cdecl argument at
    /// <c>[esp+8]</c>; execution resumes at <c>push ebp</c> (0x9cfa68).
    /// </summary>
    public static UmbraLuaCallHookPlan LinkpearlTutorialMode { get; } = new(
        "linkpearl-tutorial-mode",
        Offset: 0x9cfa60,
        ExpectedBytes: new byte[]
        {
            0x8B, 0x44, 0x24, 0x08, // mov eax, [esp+8]
            0x83, 0x78, 0x08, 0x06 // cmp dword [eax+8], 6
        },
        HeadBytes: new byte[]
        {
            0x8B, 0x44, 0x24, 0x08 // mov eax, [esp+8]
        },
        TailBytes: new byte[]
        {
            0x83, 0x78, 0x08, 0x06 // cmp dword [eax+8], 6
        });
}
